<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>'Slim'ToolWrapper - Nmap</h1>
<form action="/">
    <button>HOME</button>
</form>

<form action="/toolController/nmap" method="post">
    <h2>Target</h2>
    <label for="ip">IP or Subnet</label>
    <input type="text" name="ip" id="ip" value="localhost"><br>

    <h2>ScanType</h2>
    <label for="fast">Fast Scan (top 100 ports)</label>
    <input type="radio" name="scanType" id="fast" value="fast"><br>

    <label for="ping">Only Ping Scan</label>
    <input type="radio" name="scanType" id="ping" value="ping"><br>

    <label for="commonPorts">Common Ports</label>
    <input type="radio" name="scanType" id="commonPorts" value="commonPorts"><br>

    <label for="port">Custom Port Range/List</label>
    <input type="radio" name="scanType" id="port" value="port"><br>

    <label for="portRange"></label>
    <input type="text" name="portRange" id="portRange" placeholder="22,80" style="display:none">

    <div id="aggro">
        <h2>Aggressivity</h2>
        <label for="versionDetection">Version Detection</label>
        <input type="checkbox" name="versionDetection" id="versionDetection">

        <label for="osDetection">OS Detection</label>
        <input type="checkbox" name="osDetection" id="osDetection">

        <label for="scriptDetection">Script Detection (default)</label>
        <input type="checkbox" name="scriptDetection" id="scriptDetection">

    </div>

    <div id="timing">
        <h2>Timing and Performance</h2>
        Paranoid and Sneaky may prevent detection/alerts from IDS but they will take an extrordinary amount of time.<br>
        <select name="timing">
            <option value="-T0">Paranoid (one port at a time)</option>
            <option value="-T1">Sneaky</option>
            <option value="-T2">Polite</option>
            <option value="-T3" selected="selected">Normal</option>
            <option value="-T4">Aggressive (with decent broadband connection)</option>
            <option value="-T5">Insane</option>
        </select>

        <!-- TODO: —min-hostgroup 2048 -->
    </div>

    <div id="firewall">
        <h2>Firewall/IDS Evasion and Spoofing</h2>
        <label for="fragment">Fragment Packages</label>
        <input type="checkbox" name="fragment" id="fragment"><br>

        <label for="decoy">Decoys - It appears that other IP’s are also scanning the network</label>
        <input type="text" name="decoy" id="decoy" placeholder="194.x.x.x,194.x.x.x">

        <!-- TODO: spoof, sourceport, badsum, adler32 -->
    </div>

    <div id="otherStuff">
        <h2>Other Stuff</h2>
        <label for="verbose">Verbose Run</label>
        <input type="checkbox" name="verbose" id="verbose"><br>

        <label for="verbose">Output webXML</label>
        <input type="checkbox" name="ox" id="ox">
    </div>

    <br><button>Go..</button>
</form>

<?php if (isset($toolDependencies)) : ?>
    <br><table style="margin: 0px auto">
        <thead>
        <th>Tool</th>
        <th>Status</th>
        <th>Version</th>
        </thead>
        <tbody>
        <?php foreach ($toolDependencies as $toolName => $toolStatus) : ?>
            <tr>
                <td><?= $toolName ?></td>
                <td><?= $toolStatus["status"] ?></td>
                <td><?= $toolStatus["version"] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<script type="application/javascript" src="/js/nmap.js"></script>
</body>
</html>
