<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>SlimToolWrapper</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>'Slim'ToolWrapper</h1>

        <form action="/">
            <button>HOME</button>
        </form>
        <form action="/core/checkToolDependencies">
            <button>Check core tool dependencies</button>
        </form>
        <form action="/toolController/nmap">
            <button>Nmap Controller</button>
        </form>

        <?php if (isset($toolDependencies)) : ?>
            <br><table style="margin: 0px auto">
                <thead>
                    <th>Tool</th>
                    <th>Status</th>
                    <th>Version</th>
                </thead>
                <tbody>
                <?php foreach ($toolDependencies as $toolName => $toolStatus) : ?>
                    <tr>
                        <td><?= $toolName ?></td>
                        <td><?= $toolStatus["status"] ?></td>
                        <td><?= $toolStatus["version"] ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </body>
</html>
